data = {
  "QZ" : { "rate" : 0, "neighbors" : [ "IR", "FA" ] },
  "FV" : { "rate" : 0, "neighbors" : [ "AA", "GZ" ] },
  "GZ" : { "rate" : 0, "neighbors" : [ "FV", "PO" ] },
  "QL" : { "rate" : 0, "neighbors" : [ "MR", "AA" ] },
  "AA" : { "rate" : 0, "neighbors" : [ "QL", "GQ", "EV", "FV" ] },
  "SQ" : { "rate" : 23, "neighbors" : [ "ZG" ] },
  "PK" : { "rate" : 8, "neighbors" : [ "MN", "GN", "WF", "TY", "CX" ] },
  "GQ" : { "rate" : 0, "neighbors" : [ "AA", "MT" ] },
  "TI" : { "rate" : 22, "neighbors" : [ "GM", "CS" ] },
  "JU" : { "rate" : 17, "neighbors" : [ "TT", "RR", "UJ", "JY" ] },
  "YD" : { "rate" : 7, "neighbors" : [ "AT", "ZS", "BS" ] },
  "YB" : { "rate" : 0, "neighbors" : [ "EA", "MW" ] },
  "FA" : { "rate" : 0, "neighbors" : [ "QZ", "JT" ] },
  "TN" : { "rate" : 0, "neighbors" : [ "ZS", "PO" ] },
  "MW" : { "rate" : 0, "neighbors" : [ "YB", "YL" ] },
  "XN" : { "rate" : 0, "neighbors" : [ "VL", "VM" ] },
  "MN" : { "rate" : 0, "neighbors" : [ "PK", "TT" ] },
  "IP" : { "rate" : 9, "neighbors" : [ "YC", "SA", "CH", "PI" ] },
  "PD" : { "rate" : 0, "neighbors" : [ "YZ", "VM" ] },
  "ZS" : { "rate" : 0, "neighbors" : [ "TN", "YD" ] },
  "PC" : { "rate" : 0, "neighbors" : [ "MR", "XT" ] },
  "VM" : { "rate" : 13, "neighbors" : [ "CX", "XN", "PD" ] },
  "PO" : { "rate" : 4, "neighbors" : [ "GZ", "TN", "SA", "XT", "BM" ] },
  "GN" : { "rate" : 0, "neighbors" : [ "PK", "YL" ] },
  "YL" : { "rate" : 5, "neighbors" : [ "MT", "YZ", "GN", "SU", "MW" ] },
  "IR" : { "rate" : 6, "neighbors" : [ "LK", "PI", "BM", "QZ", "EV" ] },
  "GM" : { "rate" : 0, "neighbors" : [ "TI", "RH" ] },
  "CS" : { "rate" : 0, "neighbors" : [ "UJ", "TI" ] },
  "EA" : { "rate" : 18, "neighbors" : [ "VL", "YB", "WF", "JY" ] },
  "LK" : { "rate" : 0, "neighbors" : [ "IR", "MR" ] },
  "BM" : { "rate" : 0, "neighbors" : [ "IR", "PO" ] },
  "JZ" : { "rate" : 0, "neighbors" : [ "RH", "RR" ] },
  "SA" : { "rate" : 0, "neighbors" : [ "IP", "PO" ] },
  "XT" : { "rate" : 0, "neighbors" : [ "PO", "PC" ] },
  "YC" : { "rate" : 0, "neighbors" : [ "IP", "IL" ] },
  "RH" : { "rate" : 15, "neighbors" : [ "WJ", "JZ", "GM" ] },
  "CH" : { "rate" : 0, "neighbors" : [ "IP", "BS" ] },
  "JY" : { "rate" : 0, "neighbors" : [ "EA", "JU" ] },
  "TY" : { "rate" : 0, "neighbors" : [ "WJ", "PK" ] },
  "WJ" : { "rate" : 0, "neighbors" : [ "TY", "RH" ] },
  "IL" : { "rate" : 0, "neighbors" : [ "YC", "MR" ] },
  "BS" : { "rate" : 0, "neighbors" : [ "YD", "CH" ] },
  "AT" : { "rate" : 0, "neighbors" : [ "YD", "UX" ] },
  "UJ" : { "rate" : 0, "neighbors" : [ "CS", "JU" ] },
  "VL" : { "rate" : 0, "neighbors" : [ "EA", "XN" ] },
  "JT" : { "rate" : 21, "neighbors" : [ "ZG", "FA" ] },
  "UX" : { "rate" : 10, "neighbors" : [ "AT" ] },
  "RR" : { "rate" : 0, "neighbors" : [ "JZ", "JU" ] },
  "TT" : { "rate" : 0, "neighbors" : [ "JU", "MN" ] },
  "MT" : { "rate" : 0, "neighbors" : [ "GQ", "YL" ] },
  "EV" : { "rate" : 0, "neighbors" : [ "AA", "IR" ] },
  "ZG" : { "rate" : 0, "neighbors" : [ "JT", "SQ" ] },
  "WF" : { "rate" : 0, "neighbors" : [ "EA", "PK" ] },
  "YZ" : { "rate" : 0, "neighbors" : [ "PD", "YL" ] },
  "MR" : { "rate" : 3, "neighbors" : [ "LK", "IL", "QL", "SU", "PC" ] },
  "PI" : { "rate" : 0, "neighbors" : [ "IR", "IP" ] },
  "CX" : { "rate" : 0, "neighbors" : [ "VM", "PK" ] },
  "SU" : { "rate" : 0, "neighbors" : [ "YL", "MR" ] }
}
